"""List of allowed ServiceNow site names."""

AVAILABLE_SITES = [
    "Arctic Bay Inuujaq School",
    "Arviat John Arnalujuak High School",
    "Arviat Levi Angmak Elementary School",
    "Arviat NAC Headquarters",
    "Arviat Pana (NCC) Building, Education",
    "Arviat Qitiqliq Middle School",
    "Baker Lake Jonah Amitnaaq School",
    "Baker Lake Rachel Arngnammaktiq School",
    "Baker Lake Sanivik Building, Education",
    "Cambridge Bay Kiilinik High School",
    "Cambridge Bay Kullik Ilihakvik School",
    "Chesterfield Inlet Naja Isabelle Home",
    "Chesterfield Inlet Victor Sammurtok School",
    "Clyde River Quluaq School",
    "Coral Harbour Sakku School",
    "Gjoa Haven Qiqirtaq High School",
    "Gjoa Haven Quqshuun Elementary School",
    "Grise Fiord Umimmak School",
    "Igloolik Elementary School",
    "Igloolik High School, Desktop Unit",
    "Igloolik High School, Mobile Unit",
    "Igloolik Middle School",
    "Iqaluit Aqsarniit Middle School, 1st Floor",
    "Iqaluit Aqsarniit Middle School, 2nd Floor",
    "Iqaluit Ecole Trois Soleil",
    "Iqaluit Inuksuk High School, 1st Floor",
    "Iqaluit Inuksuk High School, 2nd Floor",
    "Iqaluit Inuksuk High School, Mobile Unit",
    "Iqaluit Joamie School",
    "Iqaluit NAC Comms Team",
    "Iqaluit NAC President's Office",
    "Iqaluit NAC President's Office Boardroom",
    "Iqaluit Nakasuk School",
    "Iqaluit Nanook School",
    "Iqaluit Sivummut, Education 2nd Floor Boardroom",
    "Iqaluit Unikkaarvik Visitor Centre",
    "Kimmirut Qaqqalik School",
    "Kinngait Kenojuak Cultural Centre",
    "Kinngait Peter Pitseolak School",
    "Kinngait Sam Pudlat School",
    "Kinngait Sam Pudlat School, Desktop Unit",
    "Kugaaruk Arviligruaq Illiniarvik School",
    "Kugluktuk Enohok Building, Education",
    "Kugluktuk High School",
    "Kugluktuk Jimmy Hikok School",
    "Naujaat Tusarvik School",
    "Naujaat Tuugaalik High School",
    "Pangnirtung Alookie School",
    "Pangnirtung Attagoyuk High School",
    "Pangnirtung NCC Building, Education",
    "Pond Inlet Aqsarniit Building, Education",
    "Pond Inlet Nasivvik High School",
    "Pond Inlet Ulaajuk School",
    "Qikiqtarjuaq Inuksuit School",
    "Rankin Inlet Kivalliq Regional Visitor Centre",
    "Rankin Inlet Leo Ussak School",
    "Rankin Inlet Maani Ulujuk School",
    "Rankin Inlet Simon Alaittuq Ford School",
    "Resolute Bay Qarmartalik School",
    "Sanikiluaq Nuiyak Elementary School",
    "Sanikiluaq Paatsaali High School",
    "Sanirajak Arnaqjuaq School",
    "Taloyoak Netsilik Ilihakvik School",
    "Whale Cove Inuglak School",
]

